### ISSUE TITLE
[Question] - Control Multiple AC with one PID Control Node

### ISSUE THREAD

**Issue by soloam** [colinl/node-red-contrib-pid#13]
Hello, I have multiple AC that I would like to control with nodered, do I need multiple PID control nodes, or can I control them all with only one PID control node and distinguish them with a value in the message (like topic)? I can pass in the message the parameters of the tuning for them.

Thank You

**Comment by colinl** [comment]
You need one PID node for each loop.

**Comment by soloam** [comment]
Thank You
