### ISSUE TITLE
suggestion /missing feature

### ISSUE THREAD

**Issue by nickeeey** [colinl/node-red-contrib-pid#20]
Hi, 
i want to use your PID Control for a PV Power Control.
The Range is 0 to 100, 
50 is 0W feed in /out
0 is > 2kw feed out 
100 >2kw feed in
but my problem is, that at night or when its shady the PID runs away and get very high values. So my only solution is a bad simple P Control....
Maybe i thought of implementing a limit for the output.
Can you realize something like that? That would be perfect for me!
Thanks

**Comment by colinl** [comment]
Sorry, I don't fully understand, remember I am not familiar with how your power system works.
What are you measuring that is used as the input to the pid (the PV)?
What does the output control?
What is the setpoint value?

Also show me how the pid node is configured.
Also attach a chart showing the pv and output values over a period.

**Comment by nickeeey** [comment]
sorry for wasting your time, i mixed up two different pid controllers and ended up at the wrong github. Please delete it (i cant)

**Comment by colinl** [comment]
If you are having problems with integral runaway, which is what this sounds like, then I suggest you try this node, as it has logic to prevent that happening.
