### ISSUE TITLE
Ability to work with negative numbers?

### ISSUE THREAD

**Issue by NorbNorb** [colinl/node-red-contrib-pid#29]
The description and the example indicate that this PID controller cannot be used with negative process variables for the input and output. I tried the example flow and set the "Output power when disabled" to -100. This value is output briefly, but then set to 0 again.
How can I use this PID controller if my process allows positive and negative values? Examples are: Position along an axis, power flow, etc.

**Comment by colinl** [comment]
Hi @NorbNorb 
The process value can be anything you like, +ve or -ve.  The output power value is always in the range 0 to 1.  For a heating type process then 0 would be no heat and 1 would be full heat.  You can scale the power to match the value you have to feed back to your process to control it.  So if you wanted the min output to be -50 and the max to be 100 then use a Range node configured to scale the range 0:1 to the range -50:100 (or 100:-50 if it is that way round).

**Comment by NorbNorb** [comment]
Thanks!

**Comment by NorbNorb** [comment]
Thanks!
