### ISSUE TITLE
Question on the proportional band

### ISSUE THREAD

**Issue by ruffieuxh** [colinl/node-red-contrib-pid#30]
Hi,

I am trying to manage the charge an discharge of my PV home battery. The "process range" - thus the input values - may go from -8000 watts (supplying to the grid) up to +8000 watts (importing from the grid).

I am not sure on how to set the proportional band value for such an operation. Would it be 16000 (-8000 to +8000) or should it be 8000?

Many thanks
Heinz

**Comment by colinl** [comment]
You might like to read through this issue https://github.com/colinl/node-red-contrib-pid/issues/28
It seems to have quite a lot in common with what you want to do.  Make sure you read right through, there were several false turns and confusions along the way.
